name: Build and Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  tag: ${{ github.ref_name }}
  
jobs:
  pyinstaller-build:
    name: Build an app
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'src/main.py'
          upload_exe_with_name: $GITHUB_REPOSITORY
          options: --onefile, --name "My App", --windowed
          
  release:    
    name: Create release
    runs-on: ubuntu-22.04
    needs: pyinstaller-build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      - name: Upload asset
        run: |
          gh release upload ${tag} "${{ job.pyinstaller-build.executable_path }}"\
          --repo="${GITHUB_REPOSITORY}" \
