name: Build and Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  pyinstaller-build:
    outputs:
      executable_path: ${{ steps.step1.outputs.executable_path }}
    name: Build an app
    runs-on: windows-latest
    steps:
      - name: Create Executable
        id: step1
        uses: sayyid5416/pyinstaller@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          tag: ${{ github.ref_name }}
        with:
          python_ver: '3.10'
          spec: 'src/App.spec'
          upload_exe_with_name: App
          options: --contents-directory "."
          
  release:    
    name: Create release
    runs-on: ubuntu-22.04
    needs: pyinstaller-build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      tag: ${{ github.ref_name }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: App
          path: app/
      - name: Display structure of downloaded files
        run: ls app/
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      - name: Archive assets
        run: |
      - name: Upload asset
        run: |
          gh release upload ${tag} app/App \
          --repo="${GITHUB_REPOSITORY}" \
