name: Test

on: push

env:
  APP_NAME: ${GITHUB_REPOSITORY#*/}

jobs:
  job1:
    name: Create release
    runs-on: ubuntu-22.04
    steps:
      - name: Echoing
        run: |
          echo "${APP_NAME}"
          
